name: tests
on: [push, pull_request]
jobs:
  tests:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Run tests
        run: tox -e py
      - name: Upload coverage
        uses: codecov/codecov-action@v1
